# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/vhdl_cpu/rtl_model/vivado_project/cpu_rtl.cache/wt [current_project]
set_property parent.project_path C:/vhdl_cpu/rtl_model/vivado_project/cpu_rtl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/vhdl_cpu/rtl_model/cpu_subprogram_pack.vhd
  C:/vhdl_cpu/rtl_model/cpu_defs_pack.vhd
  C:/vhdl_cpu/rtl_model/Test/cpu_textio_pack.vhd
  C:/vhdl_cpu/rtl_model/Test/cpu_memory_pack.vhd
  C:/vhdl_cpu/rtl_model/bootloader_program_pack.vhd
  C:/vhdl_cpu/rtl_model/logic_unit.vhd
  C:/vhdl_cpu/rtl_model/register.vhd
  C:/vhdl_cpu/rtl_model/multiplexer.vhd
  C:/vhdl_cpu/rtl_model/memory.vhd
  C:/vhdl_cpu/rtl_model/instruction_decoder.vhd
  C:/vhdl_cpu/rtl_model/adder_subcomponents.vhd
  C:/vhdl_cpu/rtl_model/adder_unit.vhd
  C:/vhdl_cpu/rtl_model/fsm.vhd
  C:/vhdl_cpu/rtl_model/InDevice.vhd
  C:/vhdl_cpu/rtl_model/inc.vhd
  C:/vhdl_cpu/rtl_model/controller.vhd
  C:/vhdl_cpu/rtl_model/shifter_unit.vhd
  C:/vhdl_cpu/rtl_model/OutDevice.vhd
  C:/vhdl_cpu/rtl_model/Test/cpu_IN_OUT_pack.vhd
  C:/vhdl_cpu/rtl_model/Test/IO_Testbench.vhd
  C:/vhdl_cpu/rtl_model/alu.vhd
  C:/vhdl_cpu/rtl_model/datapath.vhd
  C:/vhdl_cpu/rtl_model/cpu.vhd
  C:/vhdl_cpu/rtl_model/system.vhd
}
synth_design -top System -part xc7k70tfbv676-1
write_checkpoint -noxdef System.dcp
catch { report_utilization -file System_utilization_synth.rpt -pb System_utilization_synth.pb }
