# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/robert/vhdl_cpu/rtl_model/vivado_project/cpu_rtl.cache/wt [current_project]
set_property parent.project_path /home/robert/vhdl_cpu/rtl_model/vivado_project/cpu_rtl.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/robert/vhdl_cpu/rtl_model/cpu_subprogram_pack.vhd
  /home/robert/vhdl_cpu/rtl_model/cpu_defs_pack.vhd
  /home/robert/vhdl_cpu/rtl_model/logic_unit.vhd
  /home/robert/vhdl_cpu/rtl_model/alu.vhd
  /home/robert/vhdl_cpu/rtl_model/register.vhd
  /home/robert/vhdl_cpu/rtl_model/multiplexer.vhd
  /home/robert/vhdl_cpu/rtl_model/memory.vhd
  /home/robert/vhdl_cpu/rtl_model/instruction_decoder.vhd
  /home/robert/vhdl_cpu/rtl_model/datapath.vhd
  /home/robert/vhdl_cpu/rtl_model/fsm.vhd
  /home/robert/vhdl_cpu/rtl_model/adder_unit.vhd
  /home/robert/vhdl_cpu/rtl_model/adder_subcomponents.vhd
  /home/robert/vhdl_cpu/rtl_model/controller.vhd
  /home/robert/vhdl_cpu/rtl_model/InDevice.vhd
  /home/robert/vhdl_cpu/rtl_model/inc.vhd
  /home/robert/vhdl_cpu/rtl_model/cpu.vhd
  /home/robert/vhdl_cpu/rtl_model/shifter_unit.vhd
}
synth_design -top CPU_CONFIG -part xc7k70tfbv676-1
write_checkpoint -noxdef CPU_CONFIG.dcp
catch { report_utilization -file CPU_CONFIG_utilization_synth.rpt -pb CPU_CONFIG_utilization_synth.pb }
